version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Set administrator email
      PGADMIN_DEFAULT_PASSWORD: admin           # Set administrator password
    ports:
      - "5050:80"  # PgAdmin 4 default port
    networks:
      - app-network

  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi_app
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
